/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;


import com.mysql.jdbc.Connection;
import controller.authenController;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Model_User;

/**
 *
 * @author admin
 */
public class signupView extends javax.swing.JFrame {

private void showErrorDialog(String errorMessage) {
    JOptionPane.showMessageDialog(this, errorMessage, "ERROR", JOptionPane.WARNING_MESSAGE);
}
    

    public signupView() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignupForm = new javax.swing.JPanel();
        form_title = new javax.swing.JLabel();
        userName_lable = new javax.swing.JLabel();
        userName_text = new javax.swing.JTextField();
        passwordConfirm_lable = new javax.swing.JLabel();
        passwordConfirm_text = new javax.swing.JPasswordField();
        signup_btn = new javax.swing.JButton();
        password_text = new javax.swing.JPasswordField();
        password_lable1 = new javax.swing.JLabel();
        numberPhone_lable = new javax.swing.JLabel();
        numberPhone_text = new javax.swing.JTextField();
        genderFemale = new javax.swing.JCheckBox();
        genderMale = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        form_left = new javax.swing.JPanel();
        left_title = new javax.swing.JLabel();
        changeForm_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signup");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(640, 720));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        SignupForm.setBackground(new java.awt.Color(255, 255, 255));
        SignupForm.setMinimumSize(new java.awt.Dimension(640, 720));
        SignupForm.setName(""); // NOI18N
        SignupForm.setPreferredSize(new java.awt.Dimension(640, 720));

        form_title.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        form_title.setText("Đăng Ký");
        form_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        userName_lable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userName_lable.setText("Tên tài khoản");

        userName_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_textActionPerformed(evt);
            }
        });

        passwordConfirm_lable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordConfirm_lable.setText("Nhập lại mật khẩu");

        passwordConfirm_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordConfirm_textActionPerformed(evt);
            }
        });

        signup_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        signup_btn.setText("Đăng Ký");
        signup_btn.setToolTipText("");
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });

        password_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textActionPerformed(evt);
            }
        });

        password_lable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        password_lable1.setText("Mật khẩu");

        numberPhone_lable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numberPhone_lable.setText("Số điện thoại");

        numberPhone_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberPhone_textActionPerformed(evt);
            }
        });

        genderFemale.setText("Nữ");
        genderFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFemaleActionPerformed(evt);
            }
        });

        genderMale.setText("Nam");
        genderMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genderMaleMouseClicked(evt);
            }
        });
        genderMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderMaleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Giới Tính");

        javax.swing.GroupLayout SignupFormLayout = new javax.swing.GroupLayout(SignupForm);
        SignupForm.setLayout(SignupFormLayout);
        SignupFormLayout.setHorizontalGroup(
            SignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupFormLayout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupFormLayout.createSequentialGroup()
                        .addComponent(form_title)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignupFormLayout.createSequentialGroup()
                        .addGroup(SignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordConfirm_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_lable1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordConfirm_text, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberPhone_text, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberPhone_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userName_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userName_text, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SignupFormLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SignupFormLayout.createSequentialGroup()
                                .addComponent(genderMale, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(genderFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(171, 171, 171))))
        );
        SignupFormLayout.setVerticalGroup(
            SignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignupFormLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(form_title)
                .addGap(32, 32, 32)
                .addComponent(userName_lable)
                .addGap(15, 15, 15)
                .addComponent(userName_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(numberPhone_lable)
                .addGap(15, 15, 15)
                .addComponent(numberPhone_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SignupFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderMale)
                    .addComponent(genderFemale))
                .addGap(15, 15, 15)
                .addComponent(password_lable1)
                .addGap(15, 15, 15)
                .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(passwordConfirm_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(passwordConfirm_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        form_title.getAccessibleContext().setAccessibleParent(this);
        userName_text.getAccessibleContext().setAccessibleName("");
        signup_btn.getAccessibleContext().setAccessibleName("");

        getContentPane().add(SignupForm);
        SignupForm.setBounds(-110, 0, 790, 720);
        SignupForm.getAccessibleContext().setAccessibleName("form");

        form_left.setBackground(new java.awt.Color(204, 204, 255));
        form_left.setPreferredSize(new java.awt.Dimension(440, 720));

        left_title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        left_title.setText("Bạn đã có tài khoản?");

        changeForm_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        changeForm_btn.setText("Đăng Nhập");
        changeForm_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeForm_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout form_leftLayout = new javax.swing.GroupLayout(form_left);
        form_left.setLayout(form_leftLayout);
        form_leftLayout.setHorizontalGroup(
            form_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_leftLayout.createSequentialGroup()
                .addGroup(form_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(form_leftLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(changeForm_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(form_leftLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(left_title)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        form_leftLayout.setVerticalGroup(
            form_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, form_leftLayout.createSequentialGroup()
                .addContainerGap(489, Short.MAX_VALUE)
                .addComponent(left_title, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeForm_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );

        getContentPane().add(form_left);
        form_left.setBounds(680, -80, 440, 800);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        authenController controller = new authenController();
       

        String gender = genderMale.isSelected() ? "Nam" : genderFemale.isSelected() ? "Nữ" : "";
        String numberPhone = this.numberPhone_text != null ? this.numberPhone_text.getText() : "";
        String userName = this.userName_text != null ? this.userName_text.getText() : "";
        char[] passwordChars = this.password_text.getPassword();
        char[] confirmPasswordChars = this.passwordConfirm_text.getPassword();
        
        
        if (userName.trim().isEmpty() || userName.trim().length() <= 6) {
            showErrorDialog("Tài khoản không được dưới 6 ký tự!!!");
            return;
        }

        if (numberPhone.trim().isEmpty()) {
            showErrorDialog("Số điện thoại không được để trống!!!");
            return;
        }
         if (Model_User.isValidPhoneNumber(numberPhone)==false) {
            showErrorDialog("Số điện thoại không hợp lệ!!!");
            return;
        }
        int num=Model_User.convertStringToInt(numberPhone);
        
        if (passwordChars.length == 0 || new String(passwordChars).trim().isEmpty()) {
            showErrorDialog("Không được để trống mật khẩu!!!");
            return;
        }
         if (Model_User.isValidPassword(new String(passwordChars).trim())==false) {
            showErrorDialog("Mật khẩu phải có ít nhất 8 ký tự, 1 ký tự HOA, 1 ký tự thường và 1 số!!!");
            return;
        }
       if (controller.userExists(userName)!=false) {
            showErrorDialog("Tài Khoản" + userName +" đã tồn tại!!!");
            return;
        }
       if (controller.userExists(num)!=false) {
            showErrorDialog("Số điện thoại" + numberPhone +" đã tồn tại!!!");
            return;
        }
        if (gender.isEmpty()) {
            showErrorDialog("Giới tính không được để trống!!!");
            return;
        }

        if (!Arrays.equals(passwordChars, confirmPasswordChars)) {
            showErrorDialog("Mật khẩu không khớp!!!");
            return;
        }
        
        
  
        String message = controller.createUser(userName,String.valueOf(passwordChars),num,gender);
        JOptionPane.showMessageDialog(this,message, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_signup_btnActionPerformed

    private void userName_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName_textActionPerformed

    private void passwordConfirm_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordConfirm_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordConfirm_textActionPerformed

    private void changeForm_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeForm_btnActionPerformed
       loginView login = new loginView();
    this.dispose();
        
        
    }//GEN-LAST:event_changeForm_btnActionPerformed

    private void password_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textActionPerformed

    }//GEN-LAST:event_password_textActionPerformed

    private void numberPhone_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberPhone_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberPhone_textActionPerformed

    private void genderFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFemaleActionPerformed

    private void genderMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderMaleActionPerformed

    }//GEN-LAST:event_genderMaleActionPerformed

    private void genderMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genderMaleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_genderMaleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SignupForm;
    private javax.swing.JButton changeForm_btn;
    private javax.swing.JPanel form_left;
    private javax.swing.JLabel form_title;
    private javax.swing.JCheckBox genderFemale;
    private javax.swing.JCheckBox genderMale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel left_title;
    private javax.swing.JLabel numberPhone_lable;
    private javax.swing.JTextField numberPhone_text;
    private javax.swing.JLabel passwordConfirm_lable;
    private javax.swing.JPasswordField passwordConfirm_text;
    private javax.swing.JLabel password_lable1;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JButton signup_btn;
    private javax.swing.JLabel userName_lable;
    private javax.swing.JTextField userName_text;
    // End of variables declaration//GEN-END:variables
}
